{% set version = "1.3.0" %}

package:
    name: ocgis
    version: {{ version }}

source:
    git_url: https://github.com/NCPP/ocgis.git
    #git_tag: v{{ version }}
    git_tag: i415-conda-forge

build:
    number: 0
    skip: True  # [py3k]
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - fiona 1.6.3
        - netcdf4
        - numpy
        - shapely
    run:
        - python
        - cf_units
        - fiona 1.6.3
        - netcdf4
        - numpy
        - shapely
        - rtree

test:
    requires:
        - nose
    imports:
        - ocgis

about:
    home: http://ncpp.github.io/ocgis/
    license: NCSA License
    summary: OCGIS is short for OpenClimateGIS, a set of geoprocessing and calculation tools for CF-compliant climate datasets.

extra:
    recipe-maintainers:
        - bekozi
        - ocefpaf
